[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["NODE_ENV=production pnpm build", "chmod +x scripts/start.sh"]

[start]
cmd = "npx prisma db push --accept-data-loss --skip-generate && pnpm start"

[variables]
NODE_ENV = "production"
